### ISSUE TITLE
service worker

### ISSUE THREAD

**Issue by Sydney-o9** [mars/heroku-cra-node#12]
This is a great concept - thank you for taking the time to put this open source.

Quick note, I just tested it fetching the fresh `create-react-app` repo - it is using [service workers](https://developers.google.com/web/fundamentals/primers/service-workers/) .

<kbd>[react-ui/src/index.js](https://github.com/facebookincubator/create-react-app/blob/b264b8de33cb3a76d30cfc228a7a3a4218603157/packages/react-scripts/template/src/index.js)</kbd>
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```

I had to [unregister](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app) the service worker to see `/api` correctly in both Chrome and Firefox. Safari was ok because it [doesn't support Service Workers](https://jakearchibald.github.io/isserviceworkerready/) yet.

Any ideas?

![serviceworkers](https://user-images.githubusercontent.com/1480617/32361148-2b247710-c0b1-11e7-98a2-0dab6304a284.gif)

**Comment by mars** [comment]
According to the last item in the [create-react-app Offline First Considerations](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#offline-first-considerations) docs, fixing this config for this repo’s example `/api` relative API path will require ejecting.

Perhaps the best solution is to document this limitation clearly, linking to the docs for disabling/unregistering the ServiceWorker.

I personally do not use the technique demonstrated by this repo. I always run APIs as separate web apps with CORS configured. Sorry this issue slipped under my radar. Thanks for bringing it up here!

**Comment by mars** [comment]
I just ran through a fresh install from the newest create-react-app with ServiceWorker enabled (default setup) to test this issue. Here's what I observed:

* ✅ The relative `/api` calls from within the React app work correctly
* 🛑 Requesting `http://localhost:5000/api` directly responds with the whole React app, not just the JSON API response.

While the second observation is not the expected behavior, I'm not convinced this is a real issue with this project. The whole purpose of this project is to demonstrate self-hosting an API in the same app. If you want to deploy an API for use by other apps/origins, then run it and the React UI as a separate Heroku apps instead of using this single-app architecture.
