### ISSUE TITLE
Development deploying on cloud9 error

### ISSUE THREAD

**Issue by rohrseric** [mars/heroku-cra-node#28]
I am trying to get this to work on Cloud9 for development. It works on Heroku as intended.
I changed the port in server/index.js to 8080 from 5000, because this is what I think Cloud9 uses.
Following the local deployment instruction, after running the npm start in the react-ui directory, i get the error Something is already running on port 8080, and asks if you want to use another port. Then it uses port 8081.
Both ports 8080 and 8081 display the error: "Error: ENOENT: no such file or directory, stat '~/react-ui/build/index.html' at Error (native)"

**Comment by mars** [comment]
Hi @rohrseric 😃

I'm not personally familiar with Cloud9; will do my best to advise.

When developing locally, two process are used:

1. the Node server (default port 5000)
2. the React app in hot-reloading dev mode (default port 3000)

The React app must know how to reach the Node server. This is set in the React app's [`package.json` proxy property](https://github.com/mars/heroku-cra-node/blob/master/react-ui/package.json#L18). So, you'll need to update that to match the Node server's listener port, or leave them as their 5000/3000 defaults to avoid further confusion from disparity with this reference.

Just like the [README describes for Local Development](https://github.com/mars/heroku-cra-node/blob/master/README.md#user-content-local-development), both Node server & React dev processes must be running.

When deployed to Heroku, the React app is built as a static production bundle which is then served as static content from the Node server. Only a single process, the Node server is launched in the Heroku runtime.

The production bundle does not exist in dev mode, so that's why you get that ENOENT error. Instead, we run the React dev server which dynamically watches and rebuilds the bundle as the code is changed.
