### ISSUE TITLE
How to debug with vscode?

### ISSUE THREAD

**Issue by matoelorriaga** [mars/heroku-cra-node#37]
I cannot make it work for the server part..

**Comment by mars** [comment]
I do not use VSCode so don't have any quick solutions.

What kind of errors are you seeing @matoelorriaga ?

Since the Node server and the React front-end are quick literally different apps in the same repo, perhaps you need to open it as two different projects, one is the server in the root of the project, and the other in the `react-ui` subdirectory.

**Comment by matoelorriaga** [comment]
I managed to get it working.

For react app, add this inside .vscode/launch.json:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

For the server, add a new npm script, like:

```
"scripts": {
  "debug": "node --inspect server"
}
```

and then "attach to node process" using vscode.

**Comment by mars** [comment]
Thank you for the follow-up @matoelorriaga ☺️  Other VSCode folks will appreciate this!
